### ISSUE TITLE
Ruyi install 在未预装 tar 的系统上无法运行

### ISSUE THREAD

**Issue by Pagerd** [ruyisdk/ruyi#12]
## 系统环境
openEuler [23-03 qemu](https://mirror.iscas.ac.cn/openeuler/openEuler-23.03/virtual_machine_img/x86_64/)  CPU:8 Memory:8G

系统镜像未预装 tar
## 复现步骤
```
ruyi install gnu-plct gnu-plct-xthead
```
## 预期结果
```
info: package gnu-plct-0.20231118.0 installed to 
/root/.cache/ruyi/binaries/x86_64/gnu-plct-0.20231118.0

info: package gnu-plct-xthead-0.20231118.0 installed to 
/root/.cache/ruyi/binaries/x86_64/gnu-plct-xthead-0.20231118.0

```
## 实际结果
```
info: downloading 
https://mirror.iscas.ac.cn/ruyisdk/dist/RuyiSDK-20231118-PLCT-Sources-riscv64-pl
ct-linux-gnu.tar.xz to 
/root/.cache/ruyi/distfiles/RuyiSDK-20231118-PLCT-Sources-riscv64-plct-linux-gnu
.tar.xz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  232M  100  232M    0     0  16.2M      0  0:00:14  0:00:14 --:--:-- 23.2M
info: extracting RuyiSDK-20231118-PLCT-Sources-riscv64-plct-linux-gnu.tar.xz for
package gnu-plct-0.20231118.0
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/__main__.py", line 29, in <module>
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/cli/__init__.py", line 176, in main
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/pkg_cli.py", line 264, in cli_install
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/distfile.py", line 73, in unpack
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/unpack.py", line 15, in do_unpack
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/unpack.py", line 29, in do_unpack_tar
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/subprocess.py", line 389, in call
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/subprocess.py", line 1026, in __init__
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/subprocess.py", line 1950, in _execute_child
FileNotFoundError: [Errno 2] No such file or directory: 'tar'
```

需要处理系统未预装 tar 的情况

**Comment by weilinfox** [comment]
除了依赖 tar ，在解压缩 xz 格式和 zst 格式压缩包时将依赖 ``xz`` 和 ``zstd``

其中 tar 和 xz 在当前测试镜像 openEuler 2309 x86_64 riscv64 、 Ubuntu Jammy 、 Fedora 38 、 RevyOS 都有预装

在 mugen 抢先测试第三轮，观测到 RevyOS 20231009 没有预装 zstd 导致的 ``ruyi extract`` 命令失败

```
+ ruyi extract ruyisdk-demo
info: downloading 
https://mirror.iscas.ac.cn/ruyisdk/dist/ruyisdk-demo-f3d5f81e9c1ccda7ee3e4390dbe
1b17125758b5e.src.tar.zst to 
/root/.cache/ruyi/distfiles/ruyisdk-demo-f3d5f81e9c1ccda7ee3e4390dbe1b17125758b5
e.src.tar.zst
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   671  100   671    0     0   1762      0 --:--:-- --:--:-- --:--:--  1761
info: extracting 
ruyisdk-demo-f3d5f81e9c1ccda7ee3e4390dbe1b17125758b5e.src.tar.zst for package 
ruyisdk-demo-0.20231114.0
tar (child): zstd: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/__main__.py", line 29, in <module>
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/cli/__init__.py", line 176, in main
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/pkg_cli.py", line 184, in cli_extract
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/distfile.py", line 73, in unpack
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/unpack.py", line 15, in do_unpack
  File "/root/.cache/ruyi/progcache/0.2.0-alpha.20231126/ruyi/ruyipkg/unpack.py", line 31, in do_unpack_tar
RuntimeError: untar failed: command tar -x -f /root/.cache/ruyi/distfiles/ruyisdk-demo-f3d5f81e9c1ccda7ee3e4390dbe1b17125758b5e.src.tar.zst --strip-components=2 returned 2
+ CHECK_RESULT 1 0 0 'Check ruyi extract failed'
```

**Comment by weilinfox** [comment]
在 20231207 版本看， ``install`` 命令在 ``tar`` 不存在时似乎只是提示，并不会中断安装操作，直到 ``FileNotFoundError`` exception 发生。
