### ISSUE TITLE
Ruyi 0.12.0-beta.20240607 failed to fetch Pine64 Star64 Armbian image

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#156]
## Ruyi version

+ [0.12.0-beta.20240607](https://github.com/ruyisdk/ruyi/releases/tag/0.12.0-beta.20240607)

Same as https://github.com/ruyisdk/packages-index/issues/2

## Logs

```shell
$ ruyi device provision

RuyiSDK Device Provisioning Wizard

This is a wizard intended to help you install a system on your device for your
development pleasure, all with ease.

You will be asked some questions that help RuyiSDK understand your device and
your intended configuration, then packages will be downloaded and flashed onto
the device's storage, that you should somehow make available on this host
system beforehand.

Note that, as Ruyi does not run as root, but raw disk access is most likely
required to flash images, you should arrange to allow your user account sudo
access to necessary commands such as dd. Flashing will fail if the sudo
configuration does not allow so.

Continue? (y/N) y

The following devices are currently supported by the wizard. Please pick your device:

  1. Allwinner Nezha D1
  2. Canaan Kendryte K230
  3. Canaan Kendryte K510
  4. Milk-V Duo
  5. Milk-V Duo S
  6. Milk-V Mars
  7. Milk-V Mars CM
  8. Milk-V Meles
  9. Milk-V Pioneer Box
  10. Milk-V Vega
  11. Pine64 Star64
  12. SiFive HiFive Unmatched
  13. Sipeed Lichee Cluster 4A
  14. Sipeed Lichee Console 4A
  15. Sipeed LicheePi 4A
  16. Sipeed Lichee RV
  17. Sipeed LicheeRV Nano
  18. Sipeed Maix-I
  19. Sipeed Tang Mega 138K Pro
  20. StarFive VisionFive
  21. StarFive VisionFive2
  22. WCH CH32V103 EVB
  23. WCH CH32V203 EVB
  24. WCH CH32V208 EVB
  25. WCH CH32V303 EVB
  26. WCH CH32V305 EVB
  27. WCH CH32V307 EVB
  28. WCH CH582F EVB
  29. WCH CH592X EVB

Choice? (1-29) 11

The device has the following variants. Please choose the one corresponding to your hardware at hand:

  1. Pine64 Star64 (generic variant)

Choice? (1-1) 1

The following system configurations are supported by the device variant you have chosen. Please pick the one you want to put on the device:

  1. Armbian for Pine64 Star64

Choice? (1-1) 1

We are about to download and install the following packages for your device:

 * board-image/armbian-pine64-star64

Proceed? (y/N) y
Traceback (most recent call last):
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/__main__.py", line 53, in <module>
    "你可以在这个演示程序中使用和了解 ruyi device provision 的管理功能，\n"

  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/cli/__init__.py", line 319, in main
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/device/provision_cli.py", line 31, in cli_device_provision
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/device/provision_cli.py", line 107, in do_provision_interactive
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/device/provision_cli.py", line 146, in do_provision_combo_interactive
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/ruyipkg/pkg_cli.py", line 308, in do_install_atoms
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/ruyipkg/atom.py", line 74, in match_in_repo
  File "/home/hachi/.cache/ruyi/progcache/0.12.0-beta.20240607/ruyi/ruyipkg/repo.py", line 365, in get_pkg_latest_ver
ValueError: max() arg is an empty sequence
```

**Comment by xen0n** [comment]
Now only `alpha` `beta` and `rc` versions are treated as pre-releases.
