### ISSUE TITLE
ruyi admin format-manifest 接受 json 文件但处理出错

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#217]
# 影响版本

[0.20.0](https://github.com/ruyisdk/ruyi/releases/tag/0.20.0)

# 问题描述

ruyi admin 工具首先使用 admin 命令建立一个包含 distfiles 信息和 checksum 的 json 或 toml 文件，然后使用 format-manifest 将该文件格式化为 v1 版本的完整 manifest 文件。

manifest 支持 json 和 toml 格式； format-manifest 能够接受 json 和 toml 文件，但是测试发现它只能正常处理 toml 文件。

```
$ ruyi admin manifest -f toml ./testfile.txt
[[distfiles]]
name = "testfile.txt"
size = 43

[distfiles.checksums]
sha256 = "6b80fda85e1fd5be1a192c24f547e03be44d2eb83cad1d3da0dda145d9ed3068"
sha512 = "0e05d95f0928f29a1977ff6c805d091241996a1ade37cb1d975bfed42b59b6134899f0faf93d242676e36c424ea37d926b4e33270d030e55874f420fd5504c62"
$ $ ruyi admin manifest -f toml ./testfile.txt  >test.toml
$ ruyi admin format-manifest ./test.toml
$ cat test.toml
format = "v1"

[metadata]
desc = ""
vendor = { name = "", eula = "" }

[[distfiles]]
name = "testfile.txt"
size = 43

[distfiles.checksums]
sha256 = "6b80fda85e1fd5be1a192c24f547e03be44d2eb83cad1d3da0dda145d9ed3068"
sha512 = "0e05d95f0928f29a1977ff6c805d091241996a1ade37cb1d975bfed42b59b6134899f0faf93d242676e36c424ea37d926b4e33270d030e55874f420fd5504c62"
```

若使用 json 格式

```
$ ruyi admin manifest -f json ./testfile.txt
[
  {
    "name": "testfile.txt",
    "size": 43,
    "checksums": {
      "sha512": "0e05d95f0928f29a1977ff6c805d091241996a1ade37cb1d975bfed42b59b6134899f0faf93d242676e36c424ea37d926b4e33270d030e55874f420fd5504c62",
      "sha256": "6b80fda85e1fd5be1a192c24f547e03be44d2eb83cad1d3da0dda145d9ed3068"
    }
  }
]
$ ruyi admin manifest -f json ./testfile.txt  >test.json
$ ruyi admin format-manifest ./test.json
$ RUYI_DEBUG=x ruyi admin format-manifest ./test.json
debug: [2024-10-24T16:31:07.856902] trying config file from preset location: /usr/share/ruyi/config.toml                                     __init__.py:246
debug: [2024-10-24T16:31:07.864694] applying config: {'installation': {'externally_managed': True}}                                          __init__.py:238
debug: [2024-10-24T16:31:07.873085] trying config file from preset location: /usr/local/share/ruyi/config.toml                               __init__.py:246
debug: [2024-10-24T16:31:07.878780] trying config file from XDG path: /etc/xdg/ruyi/config.toml                                              __init__.py:250
debug: [2024-10-24T16:31:07.884594] trying config file from XDG path: /home/hachi/.config/kdedefaults/ruyi/config.toml                       __init__.py:250
debug: [2024-10-24T16:31:07.889675] trying config file from XDG path: /home/hachi/.config/ruyi/config.toml                                   __init__.py:250
debug: [2024-10-24T16:31:07.895271] applying config: {'packages': {'prereleases': True}, 'repo': {'remote':                                  __init__.py:238
                                    'https://gitee.com/ruyisdk/packages-index.git', 'branch': 'main'}}                                                      
debug: [2024-10-24T16:31:09.080750] __main__.__file__ = /usr/lib/python3.12/site-packages/ruyi/__main__.py, sys.executable =                 __init__.py:402
                                    /usr/bin/python, not compiled                                                                                           
debug: [2024-10-24T16:31:09.085697] argv[0] = /usr/lib/python3.12/site-packages/ruyi/__main__.py, self_exe =                                 __init__.py:405
                                    /usr/lib/python3.12/site-packages/ruyi/__main__.py                                                                      
debug: [2024-10-24T16:31:09.090532] args=Namespace(func=<function cli_admin_format_manifest at 0x70ea6ffc4400>, porcelain=False,             __init__.py:406
                                    tele_key='admin format-manifest', file=['./test.json'])                                                                 
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/ruyi/__main__.py", line 54, in <module>
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/cli/__init__.py", line 422, in main
    return func(gc, args)
           ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/ruyipkg/admin_cli.py", line 59, in cli_admin_format_manifest
    pm = PackageManifest.load_from_path(p)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/ruyipkg/pkg_manifest.py", line 412, in load_from_path
    return cls.load_json(fp)
           ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/ruyipkg/pkg_manifest.py", line 399, in load_json
    return cls(content)
           ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/ruyipkg/pkg_manifest.py", line 392, in __init__
    self._data = _translate_to_manifest_v1(data)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/ruyipkg/pkg_manifest.py", line 358, in _translate_to_manifest_v1
    fmt = obj.get("format", "")
          ^^^^^^^
AttributeError: 'list' object has no attribute 'get'
debug: [2024-10-24T16:31:09.100437] flushing telemetry to persistent store                                                                       store.py:59
debug: [2024-10-24T16:31:09.104717] persisted 1 telemetry event(s)                                                                               store.py:75
```

考虑到未来可能也不会再使用 json 格式，是否需要考虑让 format-manifest 命令也不接受 json 格式文件。

**Comment by xen0n** [comment]
这不是正确的使用方式，因为 `ruyi admin manifest` 生成的并不是完整的 manifest，而只是 manifest 的 distfile checksum 部分，所以它在“根”级别是 list 而非对象，造成了后续的失败。

正常的 JSON 元数据文件是可以被 `ruyi admin format-manifest` 处理的，实际上 packages-index 内容格式的批量转换就是如此做的，这个子命令存在的直接原因也是如此。

归根结底，可能是 `ruyi admin manifest` 的命名有误导性了：目前看来应该叫 `ruyi admin checksum` 更好。它最早是仿照 Gentoo `ebuild ./xxx.ebuild manifest` 的用法设计的，但我们的元数据文件就被称作 manifest，所以可能还是改一下为好。
