### ISSUE TITLE
配置文件中 upload_consent 似乎不生效

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#246]
# 影响版本

[0.24.0](https://github.com/ruyisdk/ruyi/releases/tag/0.24.0)

# 问题描述

在 ``~/.config/ruyi/config.toml`` 中配置下面的内容：

```toml
[telemetry]
mode = "on"
upload_consent = "2024-12-25T14:07:50+08:00"
```

提示信息依然出现：

```
warn: this ruyi installation has telemetry mode set to on, and will upload non-tracking usage information to RuyiSDK-managed servers every Sunday
info: the next upload will happen anytime ruyi is executed between 2024-12-29 08:00:00 +0800 and 2024-12-30 08:00:00 +0800
info: you can turn off telemetry uploads by setting the telemetry mode to local or off in the local config; consult the RuyiSDK documentation for details
```

**Comment by xen0n** [comment]
应该是 TOML datetime 类型，不要用双引号括起来

鉴于 `ruyi config` 与 `ruyi telemetry` 都会使用正确类型，现在我们也推荐用户使用 `ruyi telemetry` 管理这个配置了，兼容 string 类型的 `upload_consent` 还是个问题吗？

**Comment by weilinfox** [comment]
> 应该是 TOML datetime 类型，不要用双引号括起来
> 
> 鉴于 `ruyi config` 与 `ruyi telemetry` 都会使用正确类型，现在我们也推荐用户使用 `ruyi telemetry` 管理这个配置了，兼容 string 类型的 `upload_consent` 还是个问题吗？

啊我发现问题在哪了。

一开始直接复制的 README 里的配置 [upload_consent = 2024-12-02T15:61:00+08:00](https://github.com/ruyisdk/ruyi/blob/fc7f3f4b2b79b809e8b91d1359359c909df14a06/README.md?plain=1#L76)，这里有一个不存在的 ``15:61:00`` 所以炸了

```
Traceback (most recent call last):
  File "/usr/bin/ruyi", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/__main__.py", line 65, in entrypoint
    sys.exit(main(sys.argv))
             ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/cli/main.py", line 21, in main
    gc = GlobalConfig.load_from_config()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/ruyi/config/__init__.py", line 285, in load_from_config
    obj.try_apply_config_file(config_path)
  File "/usr/lib/python3.12/site-packages/ruyi/config/__init__.py", line 268, in try_apply_config_file
    data: Any = tomllib.load(fp)
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/tomllib/_parser.py", line 127, in loads
    raise suffixed_err(
tomllib.TOMLDecodeError: Expected newline or end of document after a statement (at line 13, column 28)
```

然后就用引号扩起来了。晕了。
