### ISSUE TITLE
【补充 20231030 版本 issue】 ruyi install 依赖 wget 但是该软件包在 oE 2309 未预装， ruyi 本身则没有发现安装失败

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#4]
完整测试报告 [RUYI 包管理 demo 版本测试结果](https://gitlab.inuyasha.love/weilinfox/plct-working/-/blob/master/Done/Month04/Week4/RUYI%20%E5%8C%85%E7%AE%A1%E7%90%86%20demo%20%E7%89%88%E6%9C%AC%E6%B5%8B%E8%AF%95%E7%BB%93%E6%9E%9C.md)

## 问题描述

1. ``ruyi install`` 依赖 wget 

   wget 在 openEuler 没有被预装，导致测试失败

   ```
   ++ ruyi list
   ++ grep -e '^## '
   ++ head -n 1
   ++ awk '{last_word = $NF; sub(/.$/, "", last_word); print substr(last_word, 2, length(last_word) - 1)}'
   + pkgname=plct-20231026
   + ruyi install plct-20231026
   info: downloading https://mirror.iscas.ac.cn/ruyisdk/dist/RuyiSDK-20231026-riscv64-plct-linux-gnu.tar.xz to /root/.cache/ruyi/distfiles/RuyiSDK-20231026-riscv64-plct-linux-gnu.tar.xz
   Traceback (most recent call last):
     File "/tmp/onefile_1650_1698644422_28288/ruyi/ruyipkg/distfile.py", line 19, in ensure
   FileNotFoundError: [Errno 2] No such file or directory: '/root/.cache/ruyi/distfiles/RuyiSDK-20231026-riscv64-plct-linux-gnu.tar.xz'

   During handling of the above exception, another exception occurred:

   Traceback (most recent call last):
     File "/tmp/onefile_1650_1698644422_28288/__main__.py", line 10, in <module>
     File "/tmp/onefile_1650_1698644422_28288/ruyi/cli/__init__.py", line 104, in main
     File "/tmp/onefile_1650_1698644422_28288/ruyi/ruyipkg/pkg.py", line 133, in cli_install
     File "/tmp/onefile_1650_1698644422_28288/ruyi/ruyipkg/distfile.py", line 22, in ensure
     File "/tmp/onefile_1650_1698644422_28288/ruyi/ruyipkg/distfile.py", line 64, in fetch
     File "/tmp/onefile_1650_1698644422_28288/subprocess.py", line 389, in call
     File "/tmp/onefile_1650_1698644422_28288/subprocess.py", line 1026, in __init__
     File "/tmp/onefile_1650_1698644422_28288/subprocess.py", line 1950, in _execute_child
   FileNotFoundError: [Errno 2] No such file or directory: 'wget'
   + CHECK_RESULT 1 0 0 'Check ruyi install package failed'
   ```

2. ruyi 没有检查到安装失败

   若由于未知原因安装工具链失败，再次运行 ``ruyi install`` ruyi 依然认为工具链已经安装

   ```
   + ruyi install plct-20231026
   + grep 'skipping already installed package plct-20231026'
   info: skipping already installed package plct-20231026
   + CHECK_RESULT 0 0 0 'Check ruyi install duplicate package failed'
   ```

**Comment by weilinfox** [comment]
amd.20231107 版本同时支持了 wget 和 curl ，该问题复测通过
