### ISSUE TITLE
ruyi 0.6.0 版本 RISC-V 二进制 "ImportError: libgit2.so.1.7"

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#81]
## RUYI 版本

[0.6.0-beta.20240307](https://github.com/ruyisdk/ruyi/releases/tag/0.6.0-beta.20240307) pre-release

## 问题描述

运行 ruyi update 时找不到 libgit2 动态链接库

```
# ruyi update
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/__main__.py", line 35, in <module>
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/cli/__init__.py", line 283, in main
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/cli/__init__.py", line 26, in init_argparse
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/device/provision_cli.py", line 12, in <module ruyi.device.provision_cli>
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/ruyipkg/atom.py", line 6, in <module ruyi.ruyipkg.atom>
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/ruyipkg/repo.py", line 6, in <module ruyi.ruyipkg.repo>
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/pygit2/__init__.py", line 32, in <module pygit2>
ImportError: libgit2.so.1.7: cannot open shared object file: No such file or directory
```

**Comment by xen0n** [comment]
此为 riscv64 build 的问题，amd64 无此问题。

尝试降级 riscv64 builder 基础镜像版本

**Comment by xen0n** [comment]
> 降级 riscv64 builder 基础镜像版本

并非此原因，实际原因是：PyPI 版本的 pygit2 在 amd64 与 arm64 上是以 pre-built wheel 的形式发布的，bundle 了 libgit2 等原生库。而在 riscv64 上构建 ruyi 时，pygit2 是在本地编译的，因而依赖了系统提供的 libgit2，造成运行时的 libgit2 依赖。

解决办法：需要在 riscv64 builder image 中构建并预装 pygit2 wheel。

**Comment by weilinfox** [comment]
在 x86 架构发现了另一个错误，似乎是另一个问题，新开了一个 issue https://github.com/ruyisdk/ruyi/issues/82
