### ISSUE TITLE
ruyi 0.6.0 版本 x86-64 二进制 "OpenSSL error: failed to load certificates"

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#82]
## RUYI 版本

[0.6.0-beta.20240307](https://github.com/ruyisdk/ruyi/releases/tag/0.6.0-beta.20240307) pre-release

## 问题描述

在 openEuler 2309 和 Fedora38 运行 ruyi update 出现以下错误：

```
+ ruyi update
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/__main__.py", line 35, in <module>
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/cli/__init__.py", line 283, in main
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/cli/__init__.py", line 26, in init_argparse
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/device/provision_cli.py", line 12, in <module ruyi.device.provision_cli>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/ruyipkg/atom.py", line 6, in <module ruyi.ruyipkg.atom>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/ruyi/ruyipkg/repo.py", line 6, in <module ruyi.ruyipkg.repo>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/pygit2/__init__.py", line 217, in <module pygit2>
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/pygit2/settings.py", line 57, in __init__
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/pygit2/settings.py", line 63, in _initialize_tls_certificate_locations
  File "/root/.cache/ruyi/progcache/0.6.0-beta.20240307/pygit2/settings.py", line 192, in set_ssl_cert_locations
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0)::reason(0)
```

**Comment by xen0n** [comment]
实际上已经有补偿逻辑了，可能仍然有边界情况需要处理。

看看 `RUYI_DEBUG=x ruyi` 输出啥？

**Comment by xen0n** [comment]
找到原因了：一些发行版（包括 openEuler 等在内）不提供 `libssl.so` 符号链接。

需要有更智能的方法取得系统 libssl 的精确位置

**Comment by weilinfox** [comment]
> RUYI_DEBUG=x ruyi

刚跑出来，在 Fedora38 ：

```
# RUYI_DEBUG=x ./ruyi
debug: [2024-03-11T09:44:45.982957] argv[0] = ./ruyi, self_exe =       log.py:37
                                    /root/ruyi                                  
debug: [2024-03-11T09:44:46.035932] cannot get system libssl default   log.py:37
                                    cert paths: libssl.so: cannot open          
                                    shared object file: No such file            
                                    or directory
```
