### ISSUE TITLE
ruyi 0.6.0 版本 RISC-V 二进制在 oErv 2309 报 "OpenSSL error: failed to load certificates" 

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#88]
## RUYI 版本

[0.6.0](https://github.com/ruyisdk/ruyi/releases/tag/0.6.0) riscv64 二进制

## 问题描述

RUYI 运行失败。确认 libssl 与 ca-certificates 已经安装。该问题在 oErv 2309 独立发版镜像出现，在 RevyOS riscv64 并没有复现。

```
$ RUYI_DEBUG=x ruyi --version
debug: [2024-03-14T13:53:21.802014] argv[0] = ruyi, self_exe =         log.py:37
                                    /home/openeuler/workspace/workspac          
                                    e/ruyi-mugen_ruyisdk/testcases/cli          
                                    -test/ruyi/ruyi                             
debug: [2024-03-14T13:53:23.399420] soname libssl.so not working:      log.py:37
                                    libssl.so: cannot open shared               
                                    object file: No such file or                
                                    directory                                   
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.6.0/__main__.py", line 35, in <module>
  File "/root/.cache/ruyi/progcache/0.6.0/ruyi/cli/__init__.py", line 283, in main
  File "/root/.cache/ruyi/progcache/0.6.0/ruyi/cli/__init__.py", line 26, in init_argparse
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0/ruyi/device/provision_cli.py", line 12, in <module ruyi.device.provision_cli>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0/ruyi/ruyipkg/atom.py", line 6, in <module ruyi.ruyipkg.atom>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0/ruyi/ruyipkg/repo.py", line 6, in <module ruyi.ruyipkg.repo>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.6.0/pygit2/__init__.py", line 217, in <module pygit2>
  File "/root/.cache/ruyi/progcache/0.6.0/pygit2/settings.py", line 57, in __init__
  File "/root/.cache/ruyi/progcache/0.6.0/pygit2/settings.py", line 63, in _initialize_tls_certificate_locations
  File "/root/.cache/ruyi/progcache/0.6.0/pygit2/settings.py", line 192, in set_ssl_cert_locations
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0)::reason(0)
```

**Comment by KevinMX** [comment]
Issue persists on openEuler 23.09 RISC-V (systemd-nspawn container & qemu-user) & ruyi [0.7.0-alpha.20240315](https://github.com/ruyisdk/ruyi/releases/tag/0.7.0-alpha.20240315):

![image](https://github.com/ruyisdk/ruyi/assets/17025286/32979d08-739c-48dd-91bd-5174e4939a98)

**Comment by weilinfox** [comment]
[0.7.0-alpha.20240315](https://github.com/ruyisdk/ruyi/releases/tag/0.7.0-alpha.20240315) 版本报错一致

```bash
+ ruyi --version
debug: [2024-03-20T11:53:38.052271] argv[0] = ruyi, self_exe =         log.py:37
                                    /home/openeuler/workspace/workspac          
                                    e/ruyi-mugen_ruyisdk/testcases/cli          
                                    -test/ruyi/ruyi                             
debug: [2024-03-20T11:53:39.793126] soname libssl.so not working:      log.py:37
                                    libssl.so: cannot open shared               
                                    object file: No such file or                
                                    directory                                   
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/__main__.py", line 35, in <module>
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/cli/__init__.py", line 283, in main
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/cli/__init__.py", line 26, in init_argparse
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/device/provision_cli.py", line 12, in <module ruyi.device.provision_cli>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/ruyipkg/atom.py", line 6, in <module ruyi.ruyipkg.atom>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/ruyipkg/repo.py", line 6, in <module ruyi.ruyipkg.repo>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/__init__.py", line 217, in <module pygit2>
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/settings.py", line 57, in __init__
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/settings.py", line 63, in _initialize_tls_certificate_locations
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/settings.py", line 192, in set_ssl_cert_locations
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0)::reason(0)
```
