### ISSUE TITLE
ruyi 0.7.0-alpha.20240315 版本 RISC-V 二进制在 Archlinux riscv64 报 "OpenSSL error: failed to load certificates"

### ISSUE THREAD

**Issue by weilinfox** [ruyisdk/ruyi#97]
## RUYI 版本

[ruyi-0.7.0-alpha.20240315.riscv64](https://github.com/ruyisdk/ruyi/releases/download/0.7.0-alpha.20240315/ruyi-0.7.0-alpha.20240315.riscv64)  riscv64 二进制

## 问题描述

RUYI 运行失败。报错类似但似乎是不一样的原因。

```
+ ruyi --version
debug: [2024-03-20T03:46:25.193648] argv[0] = ruyi, self_exe =         log.py:37
                                    /home/jenkins/workspace/workspace/          
                                    ruyi-mugen_ruyisdk/testcases/cli-t          
                                    est/ruyi/ruyi                               
debug: [2024-03-20T03:46:25.383433] soname libssl.so not working:      log.py:37
                                    /root/.cache/ruyi/progcache/0.7.0-          
                                    alpha.20240315/libcrypto.so.3:              
                                    version `OPENSSL_3.2.0' not found           
                                    (required by /usr/lib/libssl.so)            
Traceback (most recent call last):
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/__main__.py", line 35, in <module>
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/cli/__init__.py", line 283, in main
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/cli/__init__.py", line 26, in init_argparse
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/device/provision_cli.py", line 12, in <module ruyi.device.provision_cli>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/ruyipkg/atom.py", line 6, in <module ruyi.ruyipkg.atom>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/ruyi/ruyipkg/repo.py", line 6, in <module ruyi.ruyipkg.repo>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/__init__.py", line 217, in <module pygit2>
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/settings.py", line 57, in __init__
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/settings.py", line 63, in _initialize_tls_certificate_locations
  File "/root/.cache/ruyi/progcache/0.7.0-alpha.20240315/pygit2/settings.py", line 192, in set_ssl_cert_locations
_pygit2.GitError: OpenSSL error: failed to load certificates: error:00000000:lib(0)::reason(0)
```

**Comment by weilinfox** [comment]
说起来 ``~/.cache/ruyi/progcache/`` 下有 libssl.so 啊，为什么实际载入的是 ``/usr/lib/libssl.so`` 呢
